image: Visual Studio 2015  # образ для сборки

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

init:
  - ps: Install-Product node 10

install:
  - npm install  # команда установки зависимостей

build: off

build_script:
  - npm run build  # команда сборки

test_script:
  - npm run lint && npm run test  # скрипт тестирования

deploy_script:  # скрипт развертывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo https://%GITHUB_TOKEN%:x-oauth-basic@github.com>%USERPROFILE%\.git-credentials
  - dos2unix %USERPROFILE%\.git-credentials
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose